EVALUATE
	UNION(
		ROW(
			"Table", "Fact_Sales",
			"Column", "Date",
			"Count", COUNT('Fact_Sales'[Date]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Date]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Date]),
			"Min", MIN('Fact_Sales'[Date]),
			"Max", MAX('Fact_Sales'[Date]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					'Fact_Sales'[Date] = 0
				)),
				0
			),
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", DATEDIFF(
				MIN('Fact_Sales'[Date]),
				MAX('Fact_Sales'[Date]),
				DAY
			),
			"Range in Months", DATEDIFF(
				MIN('Fact_Sales'[Date]),
				MAX('Fact_Sales'[Date]),
				MONTH
			),
			"Range in Years", DATEDIFF(
				MIN('Fact_Sales'[Date]),
				MAX('Fact_Sales'[Date]),
				YEAR
			)
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Quantity",
			"Count", COUNT('Fact_Sales'[Quantity]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Quantity]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Quantity]),
			"Min", MIN('Fact_Sales'[Quantity]),
			"Max", MAX('Fact_Sales'[Quantity]),
			"Median", MEDIAN('Fact_Sales'[Quantity]),
			"Mean", AVERAGE('Fact_Sales'[Quantity]),
			"Standard Deviation", STDEV.P('Fact_Sales'[Quantity]),
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					'Fact_Sales'[Quantity] = 0
				)),
				0
			),
			"Evens", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[Quantity],
						2
					) = 0
				)),
				0
			),
			"Odds", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[Quantity],
						2
					) <> 0
				)),
				0
			),
			"P25", PERCENTILE.INC(
				'Fact_Sales'[Quantity],
				0.25
			),
			"P75", PERCENTILE.INC(
				'Fact_Sales'[Quantity],
				0.75
			),
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Scenario",
			"Count", COUNT('Fact_Sales'[Scenario]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Scenario]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Scenario]),
			"Min", MIN('Fact_Sales'[Scenario]),
			"Max", MAX('Fact_Sales'[Scenario]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "ItemId",
			"Count", COUNT('Fact_Sales'[ItemId]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[ItemId]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[ItemId]),
			"Min", MIN('Fact_Sales'[ItemId]),
			"Max", MAX('Fact_Sales'[ItemId]),
			"Median", MEDIAN('Fact_Sales'[ItemId]),
			"Mean", AVERAGE('Fact_Sales'[ItemId]),
			"Standard Deviation", STDEV.P('Fact_Sales'[ItemId]),
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					'Fact_Sales'[ItemId] = 0
				)),
				0
			),
			"Evens", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[ItemId],
						2
					) = 0
				)),
				0
			),
			"Odds", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[ItemId],
						2
					) <> 0
				)),
				0
			),
			"P25", PERCENTILE.INC(
				'Fact_Sales'[ItemId],
				0.25
			),
			"P75", PERCENTILE.INC(
				'Fact_Sales'[ItemId],
				0.75
			),
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Country",
			"Count", COUNT('Fact_Sales'[Country]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Country]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Country]),
			"Min", MIN('Fact_Sales'[Country]),
			"Max", MAX('Fact_Sales'[Country]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Revenue",
			"Count", COUNT('Fact_Sales'[Revenue]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Revenue]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Revenue]),
			"Min", MIN('Fact_Sales'[Revenue]),
			"Max", MAX('Fact_Sales'[Revenue]),
			"Median", MEDIAN('Fact_Sales'[Revenue]),
			"Mean", AVERAGE('Fact_Sales'[Revenue]),
			"Standard Deviation", STDEV.P('Fact_Sales'[Revenue]),
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					'Fact_Sales'[Revenue] = 0
				)),
				0
			),
			"Evens", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[Revenue],
						2
					) = 0
				)),
				0
			),
			"Odds", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[Revenue],
						2
					) <> 0
				)),
				0
			),
			"P25", PERCENTILE.INC(
				'Fact_Sales'[Revenue],
				0.25
			),
			"P75", PERCENTILE.INC(
				'Fact_Sales'[Revenue],
				0.75
			),
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "COGS",
			"Count", COUNT('Fact_Sales'[COGS]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[COGS]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[COGS]),
			"Min", MIN('Fact_Sales'[COGS]),
			"Max", MAX('Fact_Sales'[COGS]),
			"Median", MEDIAN('Fact_Sales'[COGS]),
			"Mean", AVERAGE('Fact_Sales'[COGS]),
			"Standard Deviation", STDEV.P('Fact_Sales'[COGS]),
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					'Fact_Sales'[COGS] = 0
				)),
				0
			),
			"Evens", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[COGS],
						2
					) = 0
				)),
				0
			),
			"Odds", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[COGS],
						2
					) <> 0
				)),
				0
			),
			"P25", PERCENTILE.INC(
				'Fact_Sales'[COGS],
				0.25
			),
			"P75", PERCENTILE.INC(
				'Fact_Sales'[COGS],
				0.75
			),
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Dim_Regions.Index",
			"Count", COUNT('Fact_Sales'[Dim_Regions.Index]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Dim_Regions.Index]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Dim_Regions.Index]),
			"Min", MIN('Fact_Sales'[Dim_Regions.Index]),
			"Max", MAX('Fact_Sales'[Dim_Regions.Index]),
			"Median", MEDIAN('Fact_Sales'[Dim_Regions.Index]),
			"Mean", AVERAGE('Fact_Sales'[Dim_Regions.Index]),
			"Standard Deviation", STDEV.P('Fact_Sales'[Dim_Regions.Index]),
			"Zeros", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					'Fact_Sales'[Dim_Regions.Index] = 0
				)),
				0
			),
			"Evens", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[Dim_Regions.Index],
						2
					) = 0
				)),
				0
			),
			"Odds", COALESCE(
				COUNTROWS(FILTER(
					'Fact_Sales',
					MOD(
						'Fact_Sales'[Dim_Regions.Index],
						2
					) <> 0
				)),
				0
			),
			"P25", PERCENTILE.INC(
				'Fact_Sales'[Dim_Regions.Index],
				0.25
			),
			"P75", PERCENTILE.INC(
				'Fact_Sales'[Dim_Regions.Index],
				0.75
			),
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Catalog Number",
			"Count", COUNT('Fact_Sales'[Catalog Number]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Catalog Number]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Catalog Number]),
			"Min", MIN('Fact_Sales'[Catalog Number]),
			"Max", MAX('Fact_Sales'[Catalog Number]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Region",
			"Count", COUNT('Fact_Sales'[Region]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Region]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Region]),
			"Min", MIN('Fact_Sales'[Region]),
			"Max", MAX('Fact_Sales'[Region]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		),
		ROW(
			"Table", "Fact_Sales",
			"Column", "Column 2",
			"Count", COUNT('Fact_Sales'[Column 2]),
			"Distinct Values", DISTINCTCOUNTNOBLANK('Fact_Sales'[Column 2]),
			"Null Count", COUNTROWS('Fact_Sales') - COUNT('Fact_Sales'[Column 2]),
			"Min", MIN('Fact_Sales'[Column 2]),
			"Max", MAX('Fact_Sales'[Column 2]),
			"Median", "N/A",
			"Mean", "N/A",
			"Standard Deviation", "N/A",
			"Zeros", "N/A",
			"Evens", "N/A",
			"Odds", "N/A",
			"P25", "N/A",
			"P75", "N/A",
			"Range in Days", "N/A",
			"Range in Months", "N/A",
			"Range in Years", "N/A"
		)
	)