/// Hidden parameter table for the dynamic KPI toggle slicer (Revenue, Units, COGS).
table _KPI
	isHidden
	lineageTag: fd4ec730-7f11-44b7-a7e5-068960672550

	/// KPI name displayed in the slicer (Revenue, Units, COGS).
	column KPI
		dataType: string
		isHidden
		lineageTag: b26acc76-b198-4b7b-b3a5-a2d8761889db
		summarizeBy: none
		sourceColumn: KPI
		sortByColumn: Index

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Sort order for KPI slicer items.
	column Index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c5d343d1-4f16-4410-8630-2872fd55c748
		summarizeBy: none
		sourceColumn: Index

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

	partition Dim_KPI-18308e19-7ffd-46ca-b808-be2f90c8c8d7 = m
		mode: import
		source =
				// _KPI — Static parameter table for the dynamic KPI toggle slicer.
				// Contains three rows: Revenue, Units, COGS with sort index.
				// Data is embedded as compressed Base64 (Enter Data).
				let
				    Source = Table.FromRows(
				        Json.Document(
				            Binary.Decompress(
				                Binary.FromText(
				                    "i45WCs3LLClW0lEyVIrViVYKSi1LzStNBfKNwHxnf/dgIMdYKTYWAA==",
				                    BinaryEncoding.Base64
				                ),
				                Compression.Deflate
				            )
				        ),
				        let
				            _t = ((type nullable text) meta [Serialized.Text = true])
				        in
				            type table [KPI = _t, Index = _t]
				    )
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

