table Dim_Calendar
	lineageTag: 9ee31ce7-fc82-47fe-8db7-be379824b531
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: mm/dd/yy
		lineageTag: 61d64438-ce9d-4a7b-bdfc-a2406840448b
		summarizeBy: none
		sourceColumn: Date
		sortByColumn: DateInt

		changedProperty = FormatString

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column MonthStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7948cb31-ba82-4181-a07c-3df6ed638019
		summarizeBy: none
		sourceColumn: MonthStart
		sortByColumn: MonthnYear

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEnding
		dataType: dateTime
		formatString: mm/dd/yy
		lineageTag: 22459358-2e06-4df0-b16e-3a19a5cf9ce9
		summarizeBy: none
		sourceColumn: MonthEnding
		sortByColumn: MonthnYear

		changedProperty = FormatString

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d459dd4d-ab53-4e6a-9a41-43873c96f35a
		summarizeBy: none
		sourceColumn: Year

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column QuarterOfYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 75212ac0-bbc3-4a52-8c23-2893aacc1534
		summarizeBy: none
		sourceColumn: QuarterOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quarter & Year'
		dataType: string
		lineageTag: e5960e20-4687-491a-93ce-f3ef697139c2
		summarizeBy: none
		sourceColumn: Quarter & Year
		sortByColumn: QuarterOfYear

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthOfYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6bb9c6a7-f1f4-421e-ace4-6755cda136ad
		summarizeBy: none
		sourceColumn: MonthOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column MonthShortName
		dataType: string
		lineageTag: f5d32e00-4d55-48fd-aee7-683ff52d0842
		summarizeBy: none
		sourceColumn: MonthShortName
		sortByColumn: MonthOfYear

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthnYear
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c90dec3f-ccf7-440c-b69b-1edc4ee74e50
		summarizeBy: none
		sourceColumn: MonthnYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Month-Year
		dataType: string
		lineageTag: e8eed248-9318-4b67-8b5e-580ced136dda
		summarizeBy: none
		sourceColumn: Month-Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateInt
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1b13853-f85f-4a47-bb29-cdcb22eefed6
		summarizeBy: none
		sourceColumn: DateInt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendar-c84a13df-4f81-406c-b43a-7b1629587a08 = m
		mode: import
		queryGroup: Calendar
		source =
				let
				    Source = #"Dates Version Query"(#date(2019, 1, 1), #date(2030, 12, 1), null, null),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Date", "Year", "QuarterOfYear", "Quarter & Year", "MonthOfYear", "MonthShortName", "Month-Year", "MonthnYear", "MonthEnding", "MonthStart", "DateInt"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"Date", "MonthStart", "MonthEnding", "Year", "QuarterOfYear", "Quarter & Year", "MonthOfYear", "MonthShortName", "MonthnYear", "Month-Year", "DateInt"}),
				    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each [Date] >= #date(2022, 1, 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

