table Dim_GIM
	lineageTag: b471070f-9991-498f-917e-cbf78c036660

	column 'Global PLCM Decision (Brand)' =
			
			VAR Brand = 'Dim_GIM'[Brand]
			VAR Decision = 'Dim_GIM'[Global PLCM Decision (SubBrand)]
			VAR Tbl = SUMMARIZE(FILTER( ALL('Dim_GIM'), 'Dim_GIM'[Brand] = Brand),'Dim_GIM'[Global PLCM Decision (SubBrand)])
			RETURN
			SWITCH(  CALCULATE( COUNTROWS(Tbl)), 1, IF( ISBLANK(Decision), "N/A", Decision), "Global Maintain")
		displayFolder: PLCM Decision
		lineageTag: 45486bd1-550e-48ac-a7b5-f84249502b37
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Dim_GIM","TableItemName":"Global PLCM Decision (Brand) (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Global PLCM Decision (Brand) (groups)' =
			SWITCH(
			  TRUE,
			  ISBLANK('Dim_GIM'[Global PLCM Decision (Brand)]),
			  "(Blank)",
			  'Dim_GIM'[Global PLCM Decision (Brand)] IN {"Global Exit",
			    "Local Exit"},
			  "Exit",
			  'Dim_GIM'[Global PLCM Decision (Brand)] IN {"Global Maintain"},
			  "Maintain",
			  'Dim_GIM'[Global PLCM Decision (Brand)] IN {"N/A"},
			  "Other",
			  'Dim_GIM'[Global PLCM Decision (Brand)] IN {"Out of Scope"},
			  "Out of Scope",
			  'Dim_GIM'[Global PLCM Decision (Brand)]
			)
		displayFolder: PLCM Decision
		lineageTag: 089becab-7295-48a9-9cbb-b4974298811f
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Dim_GIM"
				          }
				        },
				        "Property": "Global PLCM Decision (Brand)"
				      }
				    }
				  ]
				}

		changedProperty = IsHidden

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"g","Entity":"Dim_GIM"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"Global PLCM Decision (Brand)"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Exit","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"Global PLCM Decision (Brand)"}}],"Values":[[{"Literal":{"Value":"'Global Exit'"}}],[{"Literal":{"Value":"'Local Exit'"}}]]}}},{"DisplayName":"Maintain","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"Global PLCM Decision (Brand)"}}],"Values":[[{"Literal":{"Value":"'Global Maintain'"}}]]}}},{"DisplayName":"Other","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"Global PLCM Decision (Brand)"}}],"Values":[[{"Literal":{"Value":"'N/A'"}}]]}}},{"DisplayName":"Out of Scope","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"Global PLCM Decision (Brand)"}}],"Values":[[{"Literal":{"Value":"'Out of Scope'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	column 'Stocking Type Code'
		dataType: string
		displayFolder: Other
		lineageTag: f5fbc771-ba69-4e08-b2e1-4082bd00bbbc
		summarizeBy: none
		sourceColumn: Stocking Type Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'LCC Description'
		dataType: string
		displayFolder: Other
		lineageTag: be69ab1f-99e7-44a4-a13c-846e2df18b45
		summarizeBy: none
		sourceColumn: LCC Description
		sortByColumn: 'Life Cycle Code'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 53680b27-5578-4136-b30e-f28df63f531a
		summarizeBy: none
		sourceColumn: Brand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SubBrand
		dataType: string
		lineageTag: 8ba23758-72f9-40b7-b31c-bf5a1f113c2b
		summarizeBy: none
		sourceColumn: SubBrand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Catalog Number'
		dataType: string
		lineageTag: c0edef40-5f08-4259-9276-2c09f5a7a86b
		summarizeBy: none
		sourceColumn: Catalog Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GIM.CreateDate'
		dataType: dateTime
		formatString: mm/dd/yy
		displayFolder: SKU Dates
		lineageTag: f6caccf2-cdc7-4f11-82be-bab250d9fc92
		summarizeBy: none
		sourceColumn: GIM.CreateDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'GIM.FirstSaleDate'
		dataType: dateTime
		formatString: mm/dd/yy
		displayFolder: SKU Dates
		lineageTag: d377327d-8f06-4ea8-8aa6-065e403a5298
		summarizeBy: none
		sourceColumn: GIM.FirstSaleDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'GIM.LastChangeDate'
		dataType: dateTime
		formatString: mm/dd/yy
		displayFolder: SKU Dates
		lineageTag: 40fe20eb-5571-46dc-971b-8780dde8d50c
		summarizeBy: none
		sourceColumn: GIM.LastChangeDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'GIM.LastSaleDate'
		dataType: dateTime
		formatString: mm/dd/yy
		displayFolder: SKU Dates
		lineageTag: 63b11a67-50e9-4ea2-9715-fb560f0935ea
		summarizeBy: none
		sourceColumn: GIM.LastSaleDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'GIM.LastTransferredDate'
		dataType: dateTime
		formatString: mm/dd/yy
		displayFolder: SKU Dates
		lineageTag: 793ddfa3-ba16-41c1-a940-f5226c74679c
		summarizeBy: none
		sourceColumn: GIM.LastTransferredDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Life Cycle Code'
		dataType: string
		lineageTag: 1fae8396-7097-4c60-877b-2a83d41d06aa
		summarizeBy: none
		sourceColumn: Life Cycle Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column packcontent
		dataType: int64
		formatString: 0
		lineageTag: 0155b09d-b9bd-4c58-b5be-cc6f376413d9
		summarizeBy: sum
		sourceColumn: packcontent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Owner'
		dataType: string
		lineageTag: f29fc5d7-3b24-4069-83b0-6cda012c0030
		summarizeBy: none
		sourceColumn: Item Owner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Owner Name'
		dataType: string
		lineageTag: ead8bda6-c2c3-4d6a-9c39-b6652bf75421
		summarizeBy: none
		sourceColumn: Item Owner Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Manufacturing Cost'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b49f01e5-f58c-4b28-a9c4-d93a270e141d
		summarizeBy: none
		sourceColumn: Manufacturing Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column uomtypecode
		dataType: string
		lineageTag: c5ad98b6-9b52-4fb2-8817-0c3ed46545cf
		summarizeBy: none
		sourceColumn: uomtypecode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column packagingunitofmeasure
		dataType: int64
		formatString: 0
		lineageTag: bf9c7bb0-d6d5-411c-abbd-83f527d11537
		summarizeBy: sum
		sourceColumn: packagingunitofmeasure

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DeleteFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flag
		lineageTag: ef8dda61-a5f0-41cd-b0fc-028e414565e2
		summarizeBy: none
		sourceColumn: DeleteFlag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column activeflag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flag
		lineageTag: 867c22f2-dabc-4a89-a495-82a07cc9da1a
		summarizeBy: none
		sourceColumn: activeflag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// gim id, gim_id, gim_item_id, gim
	column ItemId
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: e75b5478-6c50-46e3-9a86-8f598fcb13a6
		summarizeBy: none
		sourceColumn: ItemId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column investigationsite
		dataType: string
		lineageTag: 69b6b6f0-a17b-4395-b4c7-27633e2e3670
		summarizeBy: none
		sourceColumn: investigationsite

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column currentmarkupclass
		dataType: string
		lineageTag: 8ce47564-293c-4d3c-8156-cd5fba866251
		summarizeBy: none
		sourceColumn: currentmarkupclass

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cemark
		dataType: string
		lineageTag: 7e737f49-4899-42b0-87d3-b2ede790f915
		summarizeBy: none
		sourceColumn: cemark

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Standard Catalog Number'
		dataType: string
		lineageTag: bc1e8785-108d-495e-b5c0-d8c7d9ed70a7
		summarizeBy: none
		sourceColumn: Standard Catalog Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Long Description'
		dataType: string
		lineageTag: 6a1ab6d5-2172-4b6e-97fc-9f7aa4916017
		summarizeBy: none
		sourceColumn: Long Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column currentproductlinecode
		dataType: string
		lineageTag: fdd01776-0870-49a4-aa27-e39349d7cf40
		summarizeBy: none
		sourceColumn: currentproductlinecode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Line'
		dataType: string
		lineageTag: 40242a56-d528-4a8f-a92a-48bda6c9cac1
		summarizeBy: none
		sourceColumn: Product Line

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Unit'
		dataType: string
		lineageTag: ad3dafa1-27db-405a-91e6-c40681a65be4
		summarizeBy: none
		sourceColumn: Business Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cymarketingcode
		dataType: string
		lineageTag: 047b2995-1365-40d2-86b7-9a269e5bea57
		summarizeBy: none
		sourceColumn: cymarketingcode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cymarketingproductgroupcode
		dataType: int64
		formatString: 0
		lineageTag: 93496167-4f6b-4c34-8453-01b7be9f52d6
		summarizeBy: sum
		sourceColumn: cymarketingproductgroupcode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cymarketingproductgroupname
		dataType: string
		lineageTag: 3784d1c6-e79b-49af-8946-431b0e6896c9
		summarizeBy: none
		sourceColumn: cymarketingproductgroupname

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cyfranchisecode
		dataType: string
		lineageTag: cd4ba3c1-9faa-4ff7-b2df-e80351fdfa42
		summarizeBy: none
		sourceColumn: cyfranchisecode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cyfranchisedescription
		dataType: string
		lineageTag: d325463f-2078-4b23-9f80-3bdfe130053b
		summarizeBy: none
		sourceColumn: cyfranchisedescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column majorclassification
		dataType: string
		lineageTag: e3761225-b69c-416a-898f-54322a027771
		summarizeBy: none
		sourceColumn: majorclassification

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column minorclassification
		dataType: string
		lineageTag: 3d0c0e20-9192-4246-8f3b-e013297afa91
		summarizeBy: none
		sourceColumn: minorclassification

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column subclassification
		dataType: string
		lineageTag: b9dbc405-e32b-4909-badb-f26141dfa653
		summarizeBy: none
		sourceColumn: subclassification

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Type Description'
		dataType: string
		lineageTag: 49f8b8b5-d878-485d-be10-a3a8e45e4e1f
		summarizeBy: none
		sourceColumn: Item Type Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ordermultiple
		dataType: int64
		formatString: 0
		lineageTag: 64b50915-f6f9-4982-8a75-314ee231012e
		summarizeBy: none
		sourceColumn: ordermultiple

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column deferredchargeflag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flag
		lineageTag: 0ccb417a-9d57-4f4c-a337-9b3efddcd0dd
		summarizeBy: none
		sourceColumn: deferredchargeflag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: d37a36ef-e5af-4331-8f3c-c26ce1c71266
		summarizeBy: sum
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column current
		dataType: string
		lineageTag: 85c16f7e-df77-4b8f-9aa5-69dac6dfb381
		summarizeBy: none
		sourceColumn: current

		annotation SummarizationSetBy = Automatic

	column PL_Brand_SubBrand_Key
		dataType: string
		lineageTag: 133f6e7d-423d-4142-93b3-68e109bfb724
		summarizeBy: none
		sourceColumn: PL_Brand_SubBrand_Key

		annotation SummarizationSetBy = Automatic

	column 'PLCM Status'
		dataType: string
		lineageTag: c9d9436e-dbb9-4399-96dc-8df9b8cc1353
		summarizeBy: none
		sourceColumn: PLCM Status

		annotation SummarizationSetBy = Automatic

	column 'US PLCM Decision'
		dataType: string
		lineageTag: 4aab00ff-d5d2-4444-9804-53391927ca43
		summarizeBy: none
		sourceColumn: US PLCM Decision

		annotation SummarizationSetBy = Automatic

	column 'EU PLCM Decision'
		dataType: string
		lineageTag: e94f1067-1383-4e51-9726-6408ece2771a
		summarizeBy: none
		sourceColumn: EU PLCM Decision

		annotation SummarizationSetBy = Automatic

	column 'ASPAC PLCM Decision'
		dataType: string
		lineageTag: ce0f68d3-58c5-4d03-aeba-c748fed8b931
		summarizeBy: none
		sourceColumn: ASPAC PLCM Decision

		annotation SummarizationSetBy = Automatic

	column 'Global PLCM Decision (SubBrand)'
		dataType: string
		lineageTag: ee88e14d-4034-4990-9f20-6650dd859e34
		summarizeBy: none
		sourceColumn: Global PLCM Decision (SubBrand)

		annotation SummarizationSetBy = Automatic

	column 'Roadmap Updated'
		dataType: string
		lineageTag: c92fa45e-64b0-4cc2-bd9b-990b2f55b52d
		summarizeBy: none
		sourceColumn: Roadmap Updated

		annotation SummarizationSetBy = Automatic

	column 'PPR.Last Buy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d814814-bfd3-4ba9-beec-d0e709972bee
		summarizeBy: none
		sourceColumn: PPR.Last Buy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'PPR.Last Sell'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9eac8644-bdf8-4a39-9b18-c0876408ffbb
		summarizeBy: none
		sourceColumn: PPR.Last Sell

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Comments
		dataType: string
		lineageTag: e9385f9a-bef2-4ae6-bee4-9aab37ca7080
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column 'PLCM Status - Exec Summary'
		dataType: string
		lineageTag: 630bace0-ffb3-4da9-99f9-0957644b48fd
		summarizeBy: none
		sourceColumn: PLCM Status - Exec Summary

		annotation SummarizationSetBy = Automatic

	hierarchy 'Franchise Hierarchy'
		lineageTag: aeb79037-8b99-4310-a4c8-ad5888a036d9

		level 'Business Unit'
			lineageTag: 71da2afb-8ce5-4c5e-8e80-7ac5af1e98b6
			column: 'Business Unit'

		level 'Product Line'
			lineageTag: 42fd5d88-b001-423d-a62c-4217b0dbd651
			column: 'Product Line'

		level Brand
			lineageTag: 1a840456-03f9-4c0a-a416-b73de4c04e5d
			column: Brand

		level SubBrand
			lineageTag: c0eb84e4-cd44-4d74-bc63-aabb7b18b0ae
			column: SubBrand

		level 'Catalog Number'
			lineageTag: 0ae4a790-18b9-4b3a-a48d-c5cf8b08ba6c
			column: 'Catalog Number'

		changedProperty = IsHidden

	partition Dim_GIM-f911bc3c-c25e-4d22-b83a-f42e4ec92347 = m
		mode: import
		queryGroup: Products
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"f4ac28b7-50fc-4635-87fe-7bd77e9652a8" = Workspaces{[workspaceId="f4ac28b7-50fc-4635-87fe-7bd77e9652a8"]}[Data],
				    #"3c4e0e8e-488e-4345-8703-b15f825bed96" = #"f4ac28b7-50fc-4635-87fe-7bd77e9652a8"{[dataflowId="3c4e0e8e-488e-4345-8703-b15f825bed96"]}[Data],
				    Dim_GIMItem_ = #"3c4e0e8e-488e-4345-8703-b15f825bed96"{[entity="Dim_GIMItem",version=""]}[Data],
				    #"Added Index" = Table.AddIndexColumn(Dim_GIMItem_, "Index", 1, 1, Int64.Type),
				    #"Merged Queries2" = Table.NestedJoin(#"Added Index", {"lifecyclecode"}, LCC_Description, {"Life Cycle Code"}, "LCC_Description", JoinKind.LeftOuter),
				    #"Expanded LCC_Description" = Table.ExpandTableColumn(#"Merged Queries2", "LCC_Description", {"LCC Description"}, {"LCC Description"}),
				    #"Added PL_Brand_SubBrand_Key" = Table.AddColumn(#"Expanded LCC_Description", "PL_Brand_SubBrand_Key", each Text.Upper(Text.Trim([cyproductgroup]) &"|"& Text.Trim([brand]) &"|"& Text.Trim([subbrand])), type text),
				    #"Merged Queries" = Table.NestedJoin(#"Added PL_Brand_SubBrand_Key", {"PL_Brand_SubBrand_Key"}, #"PPR Tracker Status", {"PL_Brand_SubBrand_Key"}, "PPR Tracker Status", JoinKind.LeftOuter),
				    #"Expanded PPR Tracker Status" = Table.ExpandTableColumn(#"Merged Queries", "PPR Tracker Status", {"PLCM Status", "US PLCM Decision", "EU PLCM Decision", "ASPAC PLCM Decision", "Global PLCM Decision (SubBrand)", "Roadmap Updated", "Last Buy", "Last Sell", "Comments", "PLCM Status - Exec Summary"}, {"PLCM Status", "US PLCM Decision", "EU PLCM Decision", "ASPAC PLCM Decision", "Global PLCM Decision (SubBrand)", "Roadmap Updated", "Last Buy", "Last Sell", "Comments", "PLCM Status - Exec Summary"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded PPR Tracker Status", {"catalognumber"}, #"Anaplan Products", {"Item Number"}, "Anaplan Products", JoinKind.LeftOuter),
				    #"Expanded Anaplan Products" = Table.ExpandTableColumn(#"Merged Queries1", "Anaplan Products", {"Stocking Type Code"}, {"Stocking Type Code"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded Anaplan Products", {"itemid"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Duplicates",{{"createdate", "GIM.CreateDate"}, {"firstsaledate", "GIM.FirstSaleDate"}, {"lastchangedate", "GIM.LastChangeDate"}, {"lastsaledate", "GIM.LastSaleDate"}, {"lasttransferreddate", "GIM.LastTransferredDate"}, {"Last Buy", "PPR.Last Buy"}, {"Last Sell", "PPR.Last Sell"},{"cyproductgroup", "Business Unit"}, {"cyproductlinename", "Product Line"}, {"cydivision", "Franchise"}, {"subbrand", "SubBrand"}, {"catalognumber", "Catalog Number"}, {"brand", "Brand"}, {"deletedflag", "DeleteFlag"}, {"lifecyclecode", "Life Cycle Code"}, {"standardcatalognumber", "Standard Catalog Number"}, {"itemownername", "Item Owner Name"}, {"itemowner", "Item Owner"}, {"itemid", "ItemId"}, {"longdescription", "Long Description"}, {"itemtypedescription", "Item Type Description"}, {"manufacturingcostusd", "Manufacturing Cost"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"GIM.LastTransferredDate", type date}, {"GIM.LastChangeDate", type date}, {"GIM.CreateDate", type date}, {"GIM.LastSaleDate", type date}, {"GIM.FirstSaleDate", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"cymedsurggroup", "Franchise", "cybusinesssector", "unitofmeasure", "uomdescription", "dimensionunitofmeasure", "item_skey", "segment", "subsegment", "replacementitem", "substituteitem", "eancode", "gtin", "catalogflag", "keyitemflag", "trueduplicateflag"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

