table Dim_PhaseActivity
	lineageTag: 2564db20-d197-4aca-a42b-91b44a417520

	column TaskId
		dataType: string
		lineageTag: cec463ca-b497-484b-aea4-f0563cddad61
		summarizeBy: none
		sourceColumn: TaskId
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Process/Tasks
		dataType: string
		lineageTag: 67d81f94-7449-4144-88ec-6974e9e2d768
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Process/Tasks

		annotation SummarizationSetBy = Automatic

	column Detail
		dataType: string
		lineageTag: 9551da63-08a3-4aec-9aad-0674ea087974
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

	column 'Phase ID'
		dataType: int64
		formatString: 0
		lineageTag: a949991d-2761-44ae-80b1-4c91aec82718
		summarizeBy: none
		sourceColumn: Phase ID

		annotation SummarizationSetBy = User

	column 'Phase Activity ID'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 83666158-1c21-4058-9234-b793e35d79c4
		summarizeBy: none
		sourceColumn: Phase Activity ID
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b7bb9a31-400a-42bf-8d5f-bbc4c31ea93c
		summarizeBy: none
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_PhaseActivity = m
		mode: import
		queryGroup: 'PLCM RACI Playbook'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7e9a6bda-7b19-48ec-ac34-1f7d14deda8c" = Workspaces{[workspaceId="7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"]}[Data],
				    #"1830a663-42fe-4d9a-bc4b-93a6ae5df183" = #"7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"{[dataflowId="1830a663-42fe-4d9a-bc4b-93a6ae5df183"]}[Data],
				    dim_Task_ = #"1830a663-42fe-4d9a-bc4b-93a6ae5df183"{[entity="dim_PhaseActivity",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dim_Task_,{{"Activity", "Process/Tasks"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"Phase Activity ID", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

