table Fact_ConsolidatedList
	lineageTag: 68208094-5a34-4fb5-ac03-13fb93f946c2

	column 'PLCM Phaseout Batch'
		dataType: string
		lineageTag: c655d1fd-5056-4d76-bd8e-dee3a906ba6d
		summarizeBy: none
		sourceColumn: PLCM Phaseout Batch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PLCM Status'
		dataType: string
		lineageTag: 78f870f6-aa23-4807-aca3-298d87479a2f
		summarizeBy: none
		sourceColumn: PLCM Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MDM Request #'
		dataType: string
		lineageTag: 9f714201-3cd4-40e5-b683-2272f8dd05b4
		summarizeBy: none
		sourceColumn: MDM Request #

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 4184ef2a-bdb2-484a-9276-1b071a38d462
		summarizeBy: none
		sourceColumn: Comments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ECR #'
		dataType: string
		lineageTag: a4e36e57-e23c-4887-9447-d7bbf8a2ae57
		summarizeBy: none
		sourceColumn: ECR #

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'LTS Date'
		dataType: string
		lineageTag: e171d7e8-b41d-4136-a642-1186b59565d4
		summarizeBy: none
		sourceColumn: LTS Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Date Submitted'
		dataType: string
		lineageTag: 2b069c6a-0aa3-4411-8b58-7781b494d193
		summarizeBy: none
		sourceColumn: Date Submitted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Unit'
		dataType: string
		isHidden
		lineageTag: bcaa5319-8397-4669-9864-77e49750b06a
		summarizeBy: none
		sourceColumn: Business Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		isHidden
		lineageTag: 38a9f6f5-b089-4b70-bad6-d82ea8634526
		summarizeBy: none
		sourceColumn: Brand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SubBrand
		dataType: string
		isHidden
		lineageTag: 79934792-ec16-41d7-a155-2bd44e0ca51f
		summarizeBy: none
		sourceColumn: SubBrand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Catalog Number'
		dataType: string
		isHidden
		lineageTag: 2b03bc03-f3a6-47e5-812a-b96ab267acee
		summarizeBy: none
		sourceColumn: Catalog Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Long Description'
		dataType: string
		lineageTag: 6ebd0e81-63aa-44fe-837f-13b9bc8ba457
		summarizeBy: none
		sourceColumn: Long Description

		annotation SummarizationSetBy = Automatic

	column 'Item Owner'
		dataType: string
		lineageTag: 2abdd213-bd3b-4bfb-a2aa-4299b54f16fa
		summarizeBy: none
		sourceColumn: Item Owner

		annotation SummarizationSetBy = Automatic

	column LCC
		dataType: string
		lineageTag: 1b523a5e-6580-482e-9df5-b31192018fce
		summarizeBy: none
		sourceColumn: LCC

		annotation SummarizationSetBy = Automatic

	column 'LCC Description'
		dataType: string
		lineageTag: 16d5c2a5-7ffd-40a6-a716-3dfd4468abe4
		summarizeBy: none
		sourceColumn: LCC Description

		annotation SummarizationSetBy = Automatic

	column 'GIM_ID (Hide)'
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: bdb9f301-5fa5-4068-8b18-c6aac3dc56c0
		summarizeBy: none
		sourceColumn: GIM_ID (Hide)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'GIM ID'
		dataType: int64
		formatString: 0
		lineageTag: e5e4c2db-8164-4d65-a95b-2436282f5578
		summarizeBy: none
		sourceColumn: GIM ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Phase ID'
		dataType: string
		isHidden
		lineageTag: 16fcd866-31a9-4d2c-8fa0-0bcbe166b6e0
		summarizeBy: none
		sourceColumn: Phase ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy 'Product Hierarchy'
		lineageTag: af543f7f-b855-4d33-8b33-6188cdd26bad

		level 'Business Unit'
			lineageTag: 0f47514f-4180-4ea4-9b59-de680c7ed62b
			column: 'Business Unit'

		level Brand
			lineageTag: 370ba3b1-e441-4687-aa18-bc18bf9c2b76
			column: Brand

		level SubBrand
			lineageTag: 44d504d1-8368-4ab0-992c-b7a5ff3c63ab
			column: SubBrand

		level 'Catalog Number'
			lineageTag: 35f0ece9-4970-4f08-b6b4-7aa32d8fd4e7
			column: 'Catalog Number'

	partition Fact_ConsolidatedList = m
		mode: import
		queryGroup: Products
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7e9a6bda-7b19-48ec-ac34-1f7d14deda8c" = Workspaces{[workspaceId="7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"]}[Data],
				    #"0da45554-39c0-4713-9400-fd465c822e18" = #"7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"{[dataflowId="0da45554-39c0-4713-9400-fd465c822e18"]}[Data],
				    Fact_ConsolidatedList_ = #"0da45554-39c0-4713-9400-fd465c822e18"{[entity="Fact_ConsolidatedList",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Fact_ConsolidatedList_,{{"LCC", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"LCC"}, LCC_Description, {"Life Cycle Code"}, "LCC_Description", JoinKind.LeftOuter),
				    #"Expanded LCC_Description" = Table.ExpandTableColumn(#"Merged Queries", "LCC_Description", {"LCC Description"}, {"LCC Description"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Expanded LCC_Description", "GIM ID", each if [GIM_ID] > 0 then [GIM_ID] else null, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"GIM_ID", "GIM_ID (Hide)"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"RowNum"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns", {"PLCM Status"}, Dim_PLCM_Status, {"PLCM Status"}, "Dim_PLCM_Status", JoinKind.LeftOuter),
				    #"Expanded Dim_PLCM_Status" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_PLCM_Status", {"Phase ID"}, {"Phase ID"})
				in
				    #"Expanded Dim_PLCM_Status"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

