table Fact_Inventory
	lineageTag: d060f7b4-47e4-43b2-b7da-ce3d56febf1a

	column 'Dim_Regions.Index'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: fa8c55ee-d968-491d-9114-f3b780a945e3
		summarizeBy: none
		sourceColumn: Dim_Regions.Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Region
		dataType: string
		isHidden
		displayFolder: Keys
		lineageTag: 4ba9abdf-5ff1-40df-9073-3ba179f881ca
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Erp_Site_Type
		dataType: string
		lineageTag: f16e9320-4155-4dd2-8b7c-a4a59ada834f
		summarizeBy: none
		sourceColumn: Erp_Site_Type

		annotation SummarizationSetBy = Automatic

	column Erp_Source_Plant
		dataType: string
		lineageTag: 9ccf908e-09e8-48bd-9edd-cd08f020e1dc
		summarizeBy: none
		sourceColumn: Erp_Source_Plant

		annotation SummarizationSetBy = Automatic

	column Entity_ID
		dataType: string
		lineageTag: ed304d5c-ed48-4e2e-a92c-79842a3b9805
		summarizeBy: none
		sourceColumn: Entity_ID

		annotation SummarizationSetBy = Automatic

	column Inventory_Status
		dataType: string
		lineageTag: 9bdffda0-98ce-4909-bc3c-12606d0e12a9
		summarizeBy: none
		sourceColumn: Inventory_Status

		annotation SummarizationSetBy = Automatic

	column Erp_Inventory_Source
		dataType: string
		lineageTag: be0a9c6b-c127-4d9b-86b2-0a7e72b11398
		summarizeBy: none
		sourceColumn: Erp_Inventory_Source

		annotation SummarizationSetBy = Automatic

	column Inventory_Category
		dataType: string
		lineageTag: ab8e7c0e-49f6-492f-a327-f51e5dc38f1c
		summarizeBy: none
		sourceColumn: Inventory_Category

		annotation SummarizationSetBy = Automatic

	column QuantityOnHand
		dataType: double
		isHidden
		lineageTag: d3182dc8-6283-48f3-bcd1-9ffb84e3181c
		summarizeBy: sum
		sourceColumn: QuantityOnHand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ERP_Extended_Statutory_Cost_USD
		dataType: double
		isHidden
		lineageTag: cff34c11-4212-4880-9d89-1200475d1dec
		summarizeBy: sum
		sourceColumn: ERP_Extended_Statutory_Cost_USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ERP_Extended_Management_Cost_USD
		dataType: double
		isHidden
		lineageTag: a42b9362-c7e0-40f3-a414-28998d277d9d
		summarizeBy: sum
		sourceColumn: ERP_Extended_Management_Cost_USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column system_name
		dataType: string
		lineageTag: 70da1448-5b5f-4e8a-96ef-ff444e3c6afa
		summarizeBy: none
		sourceColumn: system_name

		annotation SummarizationSetBy = Automatic

	column 'BP/WH Code'
		dataType: string
		lineageTag: 59d47280-d084-4481-b16c-2e2accf6257d
		summarizeBy: none
		sourceColumn: BP/WH Code

		annotation SummarizationSetBy = Automatic

	column 'BP/WH Description'
		dataType: string
		lineageTag: 827f84f6-04c3-4eb0-a7ca-c234e86790de
		summarizeBy: none
		sourceColumn: BP/WH Description

		annotation SummarizationSetBy = Automatic

	column SUBINVENTORY_CODE
		dataType: string
		lineageTag: 7a856f45-d88f-44f6-a647-74d0fcc7e6a2
		summarizeBy: none
		sourceColumn: SUBINVENTORY_CODE

		annotation SummarizationSetBy = Automatic

	column SUBINVENTORY_DESCRIPTION
		dataType: string
		lineageTag: fdd2da78-6447-4dd9-99b2-a8f1b93ded41
		summarizeBy: none
		sourceColumn: SUBINVENTORY_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column ItemId
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: 6ad9c463-40d3-49b5-b275-77768fbfb3ad
		summarizeBy: none
		sourceColumn: ItemId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_Inventory-b128650f-cd9b-485e-a6c7-709f0d42cfbe = m
		mode: import
		queryGroup: Inventory
		source =
				let
				    // Connect to Power BI Dataflows
				    Source = PowerPlatform.Dataflows(null),
				    // Connect to Power BI Dataflows
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    // Connect to Power BI Dataflows
				    #"f4ac28b7-50fc-4635-87fe-7bd77e9652a8" = Workspaces{[workspaceId="f4ac28b7-50fc-4635-87fe-7bd77e9652a8"]}[Data],
				    // Connect to Power BI Dataflows
				    #"41f287c8-3350-4c8e-996a-5a6f9956999c" = #"f4ac28b7-50fc-4635-87fe-7bd77e9652a8"{[dataflowId="41f287c8-3350-4c8e-996a-5a6f9956999c"]}[Data],
				    // Connect to Power BI Dataflows
				    fact_Inventory_ = #"41f287c8-3350-4c8e-996a-5a6f9956999c"{[entity="fact_Inventory",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(fact_Inventory_, each ([Inventory_Category] = "Finished Goods")),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"system_name", "Erp_Inventory_Source", "BP/WH Code", "BP/WH Description", "SUBINVENTORY_CODE", "SUBINVENTORY_DESCRIPTION", "Region", "Erp_Site_Type", "Erp_Source_Plant", "Entity_ID", "Inventory_Status", "Inventory_Category", "ItemId"}, {{"QuantityOnHand", each List.Sum([QuantityOnHand]), type nullable number}, {"ERP_Extended_Statutory_Cost_USD", each List.Sum([ERP_Extended_Statutory_Cost_USD]), type nullable number}, {"ERP_Extended_Management_Cost_USD", each List.Sum([ERP_Extended_Management_Cost_USD]), type nullable number}}),
				    #"Merged Queries" = Table.NestedJoin(#"Grouped Rows", {"Region"}, Dim_Regions, {"Region"}, "Dim_Regions", JoinKind.LeftOuter),
				    #"Expanded Dim_Regions" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Regions", {"Index"}, {"Dim_Regions.Index"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Dim_Regions","EUROPE","EMEA",Replacer.ReplaceText,{"Region"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

