table Fact_Sales
	lineageTag: 53a2af17-f301-4423-9df8-852efa068649

	column Date
		dataType: dateTime
		isHidden
		formatString: mm/dd/yy
		displayFolder: Keys
		lineageTag: 3fa5715d-90fb-4c21-8d28-fd63fafcc02d
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Quantity
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: ee3120e6-7fa6-4512-8ec4-9cad02e055c5
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: 2638e82b-429e-45b7-a889-a614a56fa276
		summarizeBy: none
		sourceColumn: Scenario

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemId
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: 4437f837-018b-4282-9b46-1628dfb17036
		summarizeBy: none
		sourceColumn: ItemId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 781add1f-b0ee-440f-a741-85771bde868d
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9c4ac326-f958-4d8b-9f67-7a393daedc1d
		summarizeBy: sum
		sourceColumn: Revenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COGS
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: db9d5074-6677-4a22-b0d1-8c7acacb865e
		summarizeBy: sum
		sourceColumn: COGS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dim_Regions.Index'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: bdf084ae-2893-477e-8c06-5a6382cea4d1
		summarizeBy: none
		sourceColumn: Dim_Regions.Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Catalog Number'
		dataType: string
		lineageTag: fa595c83-0333-4a88-8430-9556ea195a80
		summarizeBy: none
		sourceColumn: Catalog Number

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 344dd9aa-6a92-4593-8354-a8f3452b5c16
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Column 2' = RELATED(Dim_GIM[Business Unit])
		lineageTag: b423d397-c390-4d80-bc66-0edbbf44c9f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales-ba3cb9ec-29f4-465f-a406-9c259eaefb5e = m
		mode: import
		queryGroup: Sales/Demand
		source = ```
				let
				  // Combine the DemantraDemand and Historical Sales tables into one
				  CombinedTables = Table.Combine({DemantraDemand, #"Historical Sales"}), 
				  #"Merged Queries" = Table.NestedJoin(
				    CombinedTables, 
				    {"Region"}, 
				    Dim_Regions, 
				    {"Region"}, 
				    "Dim_Regions", 
				    JoinKind.LeftOuter
				  ), 
				  #"Expanded Dim_Regions" = Table.ExpandTableColumn(
				    #"Merged Queries", 
				    "Dim_Regions", 
				    {"Index"}, 
				    {"Dim_Regions.Index"}
				  ), 
				  #"Changed ItemId Type" = Table.TransformColumnTypes(
				    #"Expanded Dim_Regions", 
				    {{"ItemId", Int64.Type}}
				  )
				in
				  #"Changed ItemId Type"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

