table Fact_E&O
	lineageTag: acff4fb9-31e4-4475-828f-cc24a8f83607

	column Company
		dataType: string
		lineageTag: 3645d0d7-fca8-4781-8490-f2f2516f4cb2
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		isHidden
		lineageTag: 9c07324a-4467-432c-bb8c-f519c0f102e2
		summarizeBy: none
		sourceColumn: Brand

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		lineageTag: bc7badf8-795f-4e12-a79d-29af8656d520
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column MonthEnding
		dataType: dateTime
		isHidden
		formatString: mm/dd/yy
		lineageTag: 71fd73d9-eb6e-46fd-96bc-7726cc9673ae
		summarizeBy: none
		sourceColumn: MonthEnding

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Amount
		dataType: int64
		formatString: #,0
		lineageTag: 32298422-683a-4090-b23b-df30ca3974bc
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		isHidden
		lineageTag: 6bdc0d26-ecce-46c7-b811-45ee7cb0005d
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CatalogNumber
		dataType: string
		isHidden
		lineageTag: 0953b80a-4114-43be-8965-00ed9e811543
		summarizeBy: none
		sourceColumn: CatalogNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StandardCatalogNumber
		dataType: string
		isHidden
		lineageTag: ed52ee6a-44c3-4cc9-afc8-e7e0ba376572
		summarizeBy: none
		sourceColumn: StandardCatalogNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 338d0133-f489-41b4-8336-be2c2adead39
		summarizeBy: none
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ItemId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: af893c5f-ca7e-422d-9ba6-6d0045737e3c
		summarizeBy: none
		sourceColumn: ItemId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemOwner
		dataType: string
		isHidden
		lineageTag: 9285f47c-dd04-4ad4-8f77-7cd3b39f116a
		summarizeBy: none
		sourceColumn: ItemOwner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_E&O = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"7e9a6bda-7b19-48ec-ac34-1f7d14deda8c" = Workspaces{[workspaceId="7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"]}[Data],
				    #"69e3d6cc-a963-47f2-88c9-1c732d211586" = #"7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"{[dataflowId="69e3d6cc-a963-47f2-88c9-1c732d211586"]}[Data],
				    Fact_EO_ = #"69e3d6cc-a963-47f2-88c9-1c732d211586"{[entity="Fact_EO",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Fact_EO_,{{"Period", "MonthEnding"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

