/// Detailed process steps and tasks within each PLCM phaseout phase.
table 'Phase Activity'
	lineageTag: 2564db20-d197-4aca-a42b-91b44a417520

	/// Unique task identifier linking activities across tables.
	column 'Task ID'
		dataType: string
		displayFolder: Keys
		lineageTag: cec463ca-b497-484b-aea4-f0563cddad61
		summarizeBy: none
		sourceColumn: TaskId
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Name of the process or task within the phase.
	column 'Process and Tasks'
		dataType: string
		lineageTag: 67d81f94-7449-4144-88ec-6974e9e2d768
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Process/Tasks

		annotation SummarizationSetBy = Automatic

	/// Additional detail or instructions for the task.
	column Detail
		dataType: string
		lineageTag: 9551da63-08a3-4aec-9aad-0674ea087974
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

	/// Foreign key to Phase table.
	column 'Phase ID'
		dataType: int64
		formatString: 0
		displayFolder: Keys
		lineageTag: a949991d-2761-44ae-80b1-4c91aec82718
		summarizeBy: none
		sourceColumn: Phase ID

		annotation SummarizationSetBy = User

	/// Primary key. Unique identifier for the phase activity.
	column 'Phase Activity ID'
		dataType: int64
		isKey
		formatString: 0
		displayFolder: Keys
		lineageTag: 83666158-1c21-4058-9234-b793e35d79c4
		summarizeBy: none
		sourceColumn: Phase Activity ID
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Sort order within the phase.
	column Index
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: b7bb9a31-400a-42bf-8d5f-bbc4c31ea93c
		summarizeBy: none
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_PhaseActivity = m
		mode: import
		queryGroup: 'PLCM RACI Playbook'
		source =
				// Phase Activity — Process steps and tasks within each PLCM phase.
				// Source: Power BI Dataflow > dim_PhaseActivity entity
				// Renames Activity to Process/Tasks, sorts by Phase Activity ID,
				// and adds a 1-based display index for sort order in visuals.
				let
				    // ── Connect to PLCM RACI dataflow ──
				    Source = PowerPlatform.Dataflows( null ),
				    Workspaces = Source{[Id = "Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId = "7e9a6bda-7b19-48ec-ac34-1f7d14deda8c"]}[Data],
				    Dataflow = Workspace{[dataflowId = "1830a663-42fe-4d9a-bc4b-93a6ae5df183"]}[Data],
				    RawActivity = Dataflow{[entity = "dim_PhaseActivity", version = ""]}[Data],
				
				    // ── Rename source column to business-friendly name ──
				    Renamed = Table.RenameColumns(
				        RawActivity,
				        {{"Activity", "Process/Tasks"}}
				    ),
				
				    // ── Sort by Phase Activity ID for stable ordering ──
				    Sorted = Table.Sort(
				        Renamed,
				        {{"Phase Activity ID", Order.Ascending}}
				    ),
				
				    // ── Add 1-based index for visual sort order ──
				    Indexed = Table.AddIndexColumn( Sorted, "Index", 1, 1, Int64.Type )
				in
				    Indexed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

