/// Monthly revenue, COGS, and unit quantities by item, region, and scenario (Actual vs Forecast).
table Sales
	lineageTag: 53a2af17-f301-4423-9df8-852efa068649

	/// Transaction date (month-level granularity).
	column Date
		dataType: dateTime
		isHidden
		formatString: mm/dd/yy
		displayFolder: Keys
		lineageTag: 3fa5715d-90fb-4c21-8d28-fd63fafcc02d
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	/// Number of units sold in the transaction.
	column Quantity
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: ee3120e6-7fa6-4512-8ec4-9cad02e055c5
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Scenario indicator: AC = Actual, FC = Forecast.
	column Scenario
		dataType: string
		lineageTag: 2638e82b-429e-45b7-a889-a614a56fa276
		summarizeBy: none
		sourceColumn: Scenario

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Foreign key to Product table.
	column 'Item ID'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: 4437f837-018b-4282-9b46-1628dfb17036
		summarizeBy: none
		sourceColumn: ItemId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Country where the sale occurred.
	column Country
		dataType: string
		lineageTag: 781add1f-b0ee-440f-a741-85771bde868d
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Revenue amount in USD.
	column Revenue
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9c4ac326-f958-4d8b-9f67-7a393daedc1d
		summarizeBy: sum
		sourceColumn: Revenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Cost of goods sold in USD.
	column COGS
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: db9d5074-6677-4a22-b0d1-8c7acacb865e
		summarizeBy: sum
		sourceColumn: COGS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Foreign key to Region table.
	column 'Region Index'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Keys
		lineageTag: bdf084ae-2893-477e-8c06-5a6382cea4d1
		summarizeBy: none
		sourceColumn: Dim_Regions.Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Catalog number for reference (denormalized from Product).
	column 'Catalog Number'
		dataType: string
		isHidden
		lineageTag: fa595c83-0333-4a88-8430-9556ea195a80
		summarizeBy: none
		sourceColumn: Catalog Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales-ba3cb9ec-29f4-465f-a406-9c259eaefb5e = m
		mode: import
		queryGroup: Sales/Demand
		source =
				// Sales — Combined actuals + forecast transactions.
				// Merges the DemantraDemand (FC) and Historical Sales (AC) helper queries,
				// joins to the Region lookup to resolve the Region Index FK,
				// then drops the text Region column (replaced by the integer FK).
				let
				    // ── Combine actuals and forecast into one table ──
				    Combined = Table.Combine( {DemantraDemand, #"Historical Sales"} ),
				
				    // ── Join to Region lookup for integer FK ──
				    JoinedRegion = Table.NestedJoin(
				        Combined,
				        {"Region"},
				        Region,
				        {"Region"},
				        "Region.Lookup",
				        JoinKind.LeftOuter
				    ),
				    ExpandedRegion = Table.ExpandTableColumn(
				        JoinedRegion,
				        "Region.Lookup",
				        {"Index"},
				        {"Dim_Regions.Index"}
				    ),
				
				    // ── Cast ItemId to integer for reliable relationship ──
				    TypedItemId = Table.TransformColumnTypes(
				        ExpandedRegion,
				        {{"ItemId", Int64.Type}}
				    ),
				
				    // ── Drop the text Region column (FK replaces it) ──
				    Cleaned = Table.RemoveColumns( TypedItemId, {"Region"} )
				in
				    Cleaned

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

